### ISSUE TITLE
Add this package to cryptography's downstream tests.

### ISSUE THREAD

**Issue by SalusaSecondus** [awslabs/aws-dynamodb-encryption-python#2]
**DO NOT DO UNTIL PUBLIC RELEASE.**

Add this package to `pyca/cryptography`'s [downstream tests](https://github.com/pyca/cryptography/blob/master/Jenkinsfile#L106) to ensure that they do not make changes which break us.

**Comment by mattsb42-aws** [comment]
https://github.com/pyca/cryptography/pull/4280
